import type { Metadata } from "next";
import Header from '@/components/layout/header.tsx';
import Footer from '@/components/layout/footer.tsx';
import { Geist, Geist_Mono } from "next/font/google";
import "../style/app.css";


const geistSans = Geist({  variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}

